services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ./.docker/entrypoint.sh
    container_name: nogain-dev-api
    ports:
      - '5000:5000'
    volumes:
      - .:/home/node/app
      
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build: .docker/postgres
    container_name: nogain-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"